services:
  frontend:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DIRECT_URL=${DIRECT_URL}
    ports:
      - 5173:5173
    environment:
      - VITE_URL=${VITE_URL}
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
    
  backend:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DIRECT_URL=${DIRECT_URL}
    command: npx tsx server.ts
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS=${CORS}
      - URL=${URL}
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./server.ts
          action: restart
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/